### ISSUE TITLE
3/17 Crossover Review

### ISSUE THREAD

**Issue by ashwinbabu888** [rpeddakama/AP-CSA-T3#17]

**Comment by zenxha** [comment]
## Score: 1/1
Current deployed pages isn't up to date due to github pages performance issues, but we were shown their page they plan to deploy.
- 0.5/0.5 for owner requirements, pages had a section describing what requirements the owner had
- 0.5/0.5 for team roles, they included links to individual tickets for their roles for the week that were [in progress](https://github.com/rpeddakama/AP-CSA-T3/projects/1#column-17999309)

**Comment by Chris-Ru** [comment]
Scrum Team GitHub pages (1 points)

- [x] Project Owner initial requirements and derivative tangibles - (0.5/0.5) Mr Hendricks as Project Owner and outlined initial requirements in scrum board

- [x] Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task - (0.5/0.5)  [Scrum Board](https://github.com/rpeddakama/AP-CSA-T3/projects/1) with tickets and tasks within tickets for each Scrum Member
