### ISSUE TITLE
Squirrel Team Review Ticket

### ISSUE THREAD

**Issue by rpeddakama** [rpeddakama/AP-CSA-T3#43]
Presenters post review ticket by team name to #general.  We will have 4 teams present and 4 teams rotate, 2-5 minutes from booth to booth, similar to [N@tM](mailto:N@tM) style.  After 4 rotations roles will switch.  Teacher will be watching on both rotations.   You will be graded by every team that watches (4 teams) and teacher.  Score will be averaged.

- [Wiki](https://rpeddakama.github.io/AP-CSA-T3/)
- [Wireframe](https://www.figma.com/file/tpYBRxdaWXlTMiIqnNVG4B/Wireframe)
- [Presentation](https://docs.google.com/presentation/d/1ARBLzOBUQTGlDDLmNITdO7OqpJLIt6iDkzCdQZ3Ocfw/edit?usp=sharing)

Teacher will grade as follows:
- How Teacher is able to Visualize ideas...  presentations of running code, GH pages,  and concepts/visuals of future project
- How Teacher is able to understand features, Issues/Tickets, Project Board, GH Pages, time box, future features, and technicals in the project
- Overall quality, clarity and presentation of the project

**Comment by calebkimsd** [comment]
Grading from MUSICGACHA:

We believed that the presentation and information given were a strong foundation for a project. During the presentation, there was no live viewing of the official website alongside not all members were organized during the duration of the presentation.  The project was displayed on google docs rather than GH pages which is not the most ideal place to store information. The idea of the website is cool (environment GPS tracker) but the actual implementation will be cool to see in the future. 

2.7 / 3

**Comment by sarahwxie** [comment]
Points: 2.5/3

Grows:

- the presentation was very unprofessional
- Yeonjoon started speaking about homosexuality halfway through
- the presentation wasn't completed -- the homosexuality discussion interrupted it

Glows:

- the content that we did see had detailed wireframes
- the team presented their current progress
- they provided adequate content for us to understand their project

**Comment by TKperson** [comment]
## Overall 2.7/3

Glows:
* simple to understand
* short

Grows:
* presentation is too short
* where is yeonjoon
